spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: INFO
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: UWZS1TETB50M9QEEKMPC
  secretKey: MdTouo62b7CO3XCWZiKhAsT2OvjQpzDtUo8tR7NW
  bucketName: movie-fun-course

security:
  basic:
    enabled: false
  user:
    name: user
    password: password