spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: UWZS1TETB50M9QEEKMPC
  secretKey: MdTouo62b7CO3XCWZiKhAsT2OvjQpzDtUo8tR7NW
  bucketName: movie-fun-course

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies

security:
  basic:
    enabled: false